model:
  learning_rate: 2.0e-4
  weight_decay: 0
  optimizer: 'Adam' # ['Adam', 'AdamW']
  lr_scheduler: 'Constant' # ['Constant', 'Cosine']
  #lr_scheduler: 'Cosine'
  #lr_warmup: 1000
  num_samples: 27000 # 30000 * spilt_ratio
  model: 'DDIM' # ['default', 'UNet', 'VAE']
  reversed: False # if True, predict ZA from FastPM
  diffusion_num_scales: 1000 # num of steps in reverse diffusion
  base_filters: 128  # base channel in score UNet model
  ch_mult: [1, 2, 2, 2] # channel multiplier in ddim UNet model
  num_res_blocks: 2  # num of residual blocks in score UNet model
  dropout: 0.1 # dropout rate in score UNet model
  num_input_channels: 6 # 3 for x and 3 for y
  num_output_channels: 3 # 3 for y
  ema: True
  ema_rate: 0.9999
  ddim_beta: [0.0001, 0.02]
  dropout: 0.1
  sampler: "DDIM"
data:
  dataset_type: 'huggingface' # ['raw', 'huggingface']
  dataset_path: '/home/user/ckwan1/ml/huggingface_dataset'
  batch_size: 64
  num_workers: 16
  augment: True # if True, use data augmentation
  density: False # if True, use density field in tensor

trainer:
  max_epochs: 500
  gpus: 4
  num_nodes: 1
  gradient_clip_val: 1.0

wandb:
  project: "fyp"
  entity: "brianwan221-the-chinese-university-of-hong-kong"
  name: "score_model"