model:
  learning_rate: 2.0e-4
  weight_decay: 0
  optimizer: 'Adam' # ['Adam', 'AdamW']
  lr_scheduler: 'Constant' # ['Constant', 'Cosine']
  #lr_scheduler: 'Cosine'
  #lr_warmup: 1000
  num_samples: 27000 # 30000 * spilt_ratio
  model: 'ICdiffusion' # ['default', 'UNet', 'VAE']
  reversed: False # if True, predict ZA from FastPM
  diffusion_noise_sigma: 0.1
  diffusion_sigma_min: 0.01
  diffusion_sigma_max: 100.0
  diffusion_sampling_eps: 1.0e-5
  diffusion_T: 1.0
  diffusion_num_scales: 1000 # num of steps in reverse diffusion
  score_act_f: 'swish' # ['elu', 'relu', 'lrelu', 'swish'] activation function in score UNet model
  base_filters: 32  # base channel in score UNet model
  ch_mult: [1, 2, 2, 1, 1] # channel multiplier in score UNet model
  blocks_per_layer: 2  # num of residual blocks in score UNet model
  dropout: 0.1 # dropout rate in score UNet model
  num_input_channels: 2 # 3 for x and 3 for y
  num_output_channels: 1 # 3 for y
  ema: True
  ema_rate: 0.999
  standardized: True # if True, use standardized input and output
  standardized_mean_1: 1.0
  standardized_mean_2: 1.0

data:
  dataset_type: 'huggingface' # ['raw', 'huggingface']
  dataset_path: '/home/user/ckwan1/ml/hfdataset'
  batch_size: 128
  num_workers: 16
  augment: True # if True, use data augmentation
  density: True # if True, use density field in tensor
  init_density: True

trainer:
  max_epochs: 500
  gpus: 4
  num_nodes: 1
  gradient_clip_val: 1.0

wandb:
  project: "fyp"
  entity: "brianwan221-the-chinese-university-of-hong-kong"
  name: "score_model_adam_gc_init_density_individual_std1and2"