model:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  optimizer: 'AdamW' # ['Adam', 'AdamW']
  lr_scheduler: 'Constant' # ['Constant', 'Cosine']
  #lr_scheduler: 'Cosine'
  #lr_warmup: 1000
  num_samples: 27000 # 30000 * spilt_ratio
  model: 'SRVAE3D' # ['default', 'UNet', 'VAE']
  srvae_udim: 1024
  srvae_zdim: 1024
  srvae_prior: 'StandardNormal'
  reversed: False # if True, predict ZA from FastPM
  lag_loss_scale: 0.5 # scale factor for Lagrangian loss
  recon_loss_scale: 1.0 # scale factor for reconstruction loss
  kl_loss: True # if True, use KL loss
  kl_loss_scale: 1.0 # scale factor for KL loss
  kl_loss_annealing: False # if True, use KL loss annealing
  steps_per_cycle: 10000 # steps per cycle for KL loss annealing
  kl_ratio: 0.5 # ratio of annealing inside a cycle

data:
  dataset_type: 'huggingface' # ['raw', 'huggingface']
  dataset_path: '/home/user/ckwan1/ml/huggingface_dataset'
  batch_size: 64
  num_workers: 16
  augment: True # if True, use data augmentation
  density: False # if True, use density field in tensor

trainer:
  max_epochs: 500
  gpus: 4
  num_nodes: 1

wandb:
  project: "fyp"
  entity: "brianwan221-the-chinese-university-of-hong-kong"
  name: "srvae_sd"